application:
  name: cms-users-service-local
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cms_users_service
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
